name: Slack Notification
description: Send a Slack notification
inputs:
  message:
    description: The message to send. Use slack formatting.
    required: true
  slack-channel-id: # 
    description: The channel ID to send the message to. Find channel ID by right clicking on channel and selecting "Copy Link" in the Slack app.
    required: true
  slack-bot-token:
    description: The Slack bot token. Find it in the Slack app definition under "OAuth & Permissions" on https://api.slack.com/apps/
    required: true

runs:
  using: composite
  steps:
    - name: Send Slack notification
      id: send-slack-notification
      shell: bash
      env:
        MESSAGE: ${{ inputs.message }}
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        SLACK_CHANNEL_ID: ${{ inputs.slack-channel-id }}
      run: |
        curl -s -X POST \
          --url "https://slack.com/api/chat.postMessage" \
          --data "{\"channel\":\"$SLACK_CHANNEL_ID\",\"text\":\"$MESSAGE\"}" \
          --header "Authorization: Bearer ${SLACK_BOT_TOKEN}" \
          --header "Content-Type: application/json; charset=utf-8"
