name: Test Action
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Action
        uses: hilli/slack-notification-action@main
        with:
          message: ":large_green_circle: Hello World :wave:"
          slack-channel-id: $${{ vars.TESTING_CHANNEL_ID }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
