name: Test Action
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Action
        uses: hilli/slack-notification-action@main
        with:
          message: "Hello World"
          channel: "ops"
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
